<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUeXImRg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUeXImRg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUeXImRg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUeXImRg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUeXImRg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UeXImRg',
    'container.build_id' => 'b720e9d9',
    'container.build_time' => 1586270591,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUeXImRg');
