<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'api_register' => [[], ['_controller' => 'App\\Controller\\Api\\UserController::register'], [], [['text', '/api/register']], [], []],
    'api_login' => [[], ['_controller' => 'App\\Controller\\Api\\UserController::login'], [], [['text', '/api/login']], [], []],
    'api_user' => [['id'], ['_controller' => 'App\\Controller\\Api\\UserController::getUserById'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/api/user']], [], []],
    'api_profile' => [[], ['_controller' => 'App\\Controller\\Api\\UserController::profile'], [], [['text', '/api/profile']], [], []],
    'api_home' => [[], ['_controller' => 'App\\Controller\\Api\\UserController::home'], [], [['text', '/api/']], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::dashboardAction'], [], [['text', '/']], [], []],
    'api_addelement' => [[], ['_controller' => 'App\\Controller\\ElementController::register'], [], [['text', '/addelement']], [], []],
    'element' => [[], ['_controller' => 'App\\Controller\\ElementController::index'], [], [['text', '/element']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_forgottenPassword' => [[], ['_controller' => 'App\\Controller\\SecurityController::forgottenPassword'], [], [['text', '/forgottenPassword']], [], []],
    'app_reset_password' => [[], ['_controller' => 'App\\Controller\\SecurityController::resetPassword'], [], [['text', '/resetPassword']], [], []],
    'api_logout' => [[], [], [], [['text', '/logout']], [], []],
];
